site_name: HPBLUP Manual
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.sections
    - toc.integrate

nav:
  - Home: index.md
  - Manual: manual_cleaned.md

markdown_extensions:
- attr_list
- toc:
    permalink: true
- tables
- fenced_code

plugins:
  - search
