site_name: HPBLUP Manual
#docs_dir: ExtractedManuals (change later after testing)
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.sections
    - toc.integrate

nav:
  - Home: index.md
  - Manual: manual_cleaned.md

hide:
 - path
 - title

markdown_extensions:
- attr_list
- toc:
    permalink: false
- tables
- fenced_code
